version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.example
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-db}
      PGUSER: ${POSTGRES_USER:-postgres}
      PGPASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATABASE: ${POSTGRES_NAME:-db}
    ports:
      - ${POSTGRES_PORT:-5432}:5432


  web:
    build:
      dockerfile: docker/Dockerfile
      context: ./
    command: bash ./run.sh
    ports:
      - ${WEB_PORT:-5000}:5000
    env_file: .env.example
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

volumes:
  db_data:
